Feature/solicitudes
Cybord-dev/caja-ahorro-isbg pull request #3
Opened 2020-09-17 19:34 UTC by TortaDosPorUno

:0

2020-09-17 19:36 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/PrestamoController.java
> +	@GetMapping("/{idUsuario}/prestamo")
usar plurales  `prestamos`

2020-09-17 19:38 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	@GetMapping
para todos los roles es solo `/roles`

aqui deberia de ser `/usuarios/{idusario}/roles`

2020-09-17 19:38 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	@PostMapping("/{idUsuario}")
el post es
`/usuarios/{idusario}/roles`

2020-09-17 19:39 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	@GetMapping("/{idUsuario}")
`/usuarios/{idusario}/roles`

2020-09-17 19:39 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	@DeleteMapping("/{idRol}/{idUsuario}")
/usuarios/{idusario}/roles/{id_role}

2020-09-17 19:41 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/SaldoAhorroController.java
> +@RequestMapping("saldoAhorro/usuarios/")
los veo todos bien- solo remueve `saldoAhorro`

2020-09-17 19:42 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	@GetMapping("/all")
No es necesario poner `/all`, con solo poner `""` es suficiente

2020-09-17 19:42 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	public ResponseEntity<UsuariosDto> NewUsuarios(@RequestBody @Valid UsuariosDto usuarioDto) {
respetar camelCase, aqui seria algo como createUsario

2020-09-17 19:43 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	@PutMapping
falta `/{idUser}`

2020-09-17 19:44 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	@PutMapping("/datos")
falto `/datos/{idUsuario}`

2020-09-17 19:45 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	@DeleteMapping("/datos/{id}")
bien

2020-09-17 19:47 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	private UsuariosService service;
Separar  en 4 servicios la lógica de usuarios, solicitudes, validaciones

2020-09-17 19:49 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	/**Solicitudes**/
Mejor separa  todos los endpoints de solicitudes, en un controlador por separado

2020-09-17 19:50 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	/*Validaciones*/
Mejor separa  todos los endpoints de validaciones, en un controlador por separado

2020-09-17 19:50 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	/*Atributos-Solicitud*/
Mejor separa  todos los endpoints de atributos, en un controlador por separado

2020-09-17 19:52 UTC, ralfdemoledor requested changes
talvez necesitemos revisar mas o menos algunos puntos

2020-09-17 22:18 UTC, TortaDosPorUno commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +	@PutMapping
acá lo voy a jalar del dto ya que siempre va ir junto al el id usuario al dtoUsuario

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<List<AtributoSolicitudDto>> getSolicitudById() {
no debe llamarse getByID si no tiene parámetro

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> crearAtributoById(@PathVariable Integer id_usuario,@PathVariable Integer id_solicitud, @RequestBody @Valid AtributoSolicitudDto atributo) {
no debe llamarse crearAtributoById , si es create se queda así, a secas

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> actualizarAtributoById(@PathVariable Integer id_usuario, @PathVariable Integer id_solicitud,@PathVariable Integer id_atributo,  @RequestBody @Valid Atribu
La actualización siempre es por id, renombrar a actualizarAtributo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<List<AtributoSolicitudDto>> getSolicitudById() {
Renombrar a getAtributos

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +	public AtributoSolicitudDto getAtributoSolicitudById(int id_usuario, int id_solicitud, int id_atributo) {
Este método no tiene sentido , si es por id, no se requiere mas attributos , ya que es un autoincrement

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	AtributoSolicitudService service;
atributos bean son privados

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	UsuariosService serviceUsuario;
atributos bean son privados

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<List<AtributoSolicitudDto>> getSolicitudById() {
Este endpoint deberia ser GET /usuarios/{id_user}/solicitudes/{id_solicitud}/atributos , traer todos los atributos de una solicitud

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> crearAtributoById(@PathVariable Integer id_usuario,@PathVariable Integer id_solicitud, @RequestBody @Valid AtributoSolicitudDto atributo) {
crearAtributo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> actualizarAtributoById(@PathVariable Integer id_usuario, @PathVariable Integer id_solicitud,@PathVariable Integer id_atributo,  @RequestBody @Valid Atribu
LA variable  debe ser camel case id_solicitud-> idSolicitud
La variable  debe ser camel case id_atributo-> idSatributo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +		return new ResponseEntity<>(serviceUsuario.getAtributoSolicitudById(id_usuario, id_solicitud, id_atributo), HttpStatus.OK);
LA variable debe ser camel case id_solicitud-> idSolicitud
La variable debe ser camel case id_atributo-> idSatributo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<Void> deleteAtributoSolicitudById(@PathVariable Integer id_usuario, @PathVariable Integer id_solicitud,@PathVariable Integer id_atributo) {
Los delete no debe nombrarse byID siempre llevan  id

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<Void> deleteAtributoSolicitudById(@PathVariable Integer id_usuario, @PathVariable Integer id_solicitud,@PathVariable Integer id_atributo) {
Cambiar la ruta /atributos/{id_atributo} , actualizar el documento

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> actualizarAtributoById(@PathVariable Integer id_usuario, @PathVariable Integer id_solicitud,@PathVariable Integer id_atributo,  @RequestBody @Valid Atribu
Cambiar ruta a atributos/{id_atributo} y actualizar el documento

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +		serviceUsuario.deleteAtributoSolicitudById(id_usuario, id_solicitud, id_atributo);
LA variable debe ser camel case id_solicitud-> idSolicitud
La variable debe ser camel case id_atributo-> idSatributo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/CatalogoPropiedadController.java
> +	public ResponseEntity<List<CatalogoPropiedadDto>> getCatPropiedadByTipo(@PathVariable String tipo){
renombrar metodoo getCatalogoByTipo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/CatalogoPropiedadController.java
> +	public ResponseEntity<CatalogoPropiedadDto> getCatPropiedadByTipoAndNombre(@PathVariable String tipo, @PathVariable String nombre){
renombrar metodoo getCatalogoByTipoAndNombre

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/CatalogoPropiedadController.java
> +	public ResponseEntity<CatalogoPropiedadDto> createCatalogoPropiedad(@RequestBody @Validated CatalogoPropiedadDto dto){
Cambiar el nombre createCatalogoPropiedad a createCatalogo

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/CatalogoPropiedadController.java
> +	public ResponseEntity<Void> deleteCatalogoByTipoAndNombre(@PathVariable String tipo, @PathVariable String nombre) {
renombrar metodo a getCatalogoByTipoAndNombre

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/PrestamoController.java
> +	public ResponseEntity<List<PrestamoDto>> getPrestamosdeUnUsuarioPorSuId(@PathVariable Integer idUsuario) {
Cambiar nombre getPrestamosdeUnUsuarioPorSuId a getPrestamosByUsuario o getPrestamosdeUsuario

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/PrestamoController.java
> +	public ResponseEntity<PrestamoDto> insertPrestamo(@PathVariable Integer idUsuario,@RequestBody @Valid PrestamoDto Dto) {
estandarizar el nombre a insert o post o crear

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/PrestamoController.java
> +
Falta el endpoint /{idUsuario}/prestamos/{idPrestamo}/saldos/

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RecursoController.java
> +
Falta el get byId /recursos/{id}

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	public ResponseEntity<List<RolDto>> getRolesController() {
este  endpoint deberia ser solamente /roles

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	public ResponseEntity<RolDto> insertNuevoRolController(@PathVariable Integer idUsuario,@RequestBody @Valid RolDto rolDto) {
cambiar nombre insertNuevoRolController a insertRol

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	public ResponseEntity<List<RolDto>> getRolesByUserIdController(@PathVariable Integer idUsuario) {
cambiar nombre getRolesByUserIdController a getRolesByUserId

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RolController.java
> +	@DeleteMapping("/{idUsuario}/roles/{idRol}")
Cambiar path /usuarios/{idUsuario}/roles/{idRol} a /roles/{idRol}

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +		return new ResponseEntity<>(serviceUsuario.createAtributoSolicitud(id_usuario, id_solicitud, atributo), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/AtributoSolicitudController.java
> +	public ResponseEntity<AtributoSolicitudDto> crearAtributoById(@PathVariable Integer id_usuario,@PathVariable Integer id_solicitud, @RequestBody @Valid AtributoSolicitudDto atributo) {
LA variable  debe ser camel case id_solicitud-> idSolicitud

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/CatalogoPropiedadController.java
> +		return new ResponseEntity<>(service.createCatalogoPropiedad(dto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/PrestamoController.java
> +		return new ResponseEntity<>(service.insertPrestamo(idUsuario,Dto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RecursoController.java
> +		return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Alguien lo copio del invoice 👍

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/RolController.java
> +		return new ResponseEntity<>(service.insertNuevoRol(idUsuario,rolDto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SaldoAhorroController.java
> +		return new ResponseEntity<>(service.insertSadoAhorro(idUsuario,Dto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +		return new ResponseEntity<>(serviceUsuario.crearSolicitudUsuario(id_usuario, solicitudDto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +		return new ResponseEntity<>(service.insertarNuevoUsuario(usuarioDto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +		return new ResponseEntity<>(service.insertarNuevoDatoUsuario(datousuarioDto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +		return new ResponseEntity<>(serviceUsuario.crearValidacion(id_usuario,id_solicitud, validacionDto), HttpStatus.OK);
Los post regresan un HttpStatus.Created->201

2020-09-20 17:54 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/AtributoSolicitud.java
> +    @JoinColumn(name="id_solicitud", insertable=false, updatable=false)
identar codigo

2020-09-20 17:59 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/services/ValidacionService.java
> +		repositoryValidacion.findAll().forEach(validaciones::add);
por que hacen esto? `repositoryValidacion.findAll()` ya regersa una lista

2020-09-20 18:00 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/services/ValidacionService.java
> +		return mapper.ValidacionDtoToValidacion(validaciones.stream());
respetar camel case  y el metodo deberia de ser `mapper.entitiesToValidationDto`

2020-09-20 18:01 UTC, ralfdemoledor commented on src/main/resources/data.sql
> +INSERT INTO VALIDACIONES(id_validacion,id_solicitud,numero_validacion,id_usuario,estatus,tipo_validacion,fecha_creacion,fecha_actualizacion) VALUES (1,1,1,2,1,'RH','2020-09-12 00:00:00','2020-09-12 0
Nunca probaron , saldos ni ahorros, donde estan los inserts?

2020-09-20 18:03 UTC, ralfdemoledor commented on src/main/resources/data.sql
> +INSERT INTO VALIDACIONES(id_validacion,id_solicitud,numero_validacion,id_usuario,estatus,tipo_validacion,fecha_creacion,fecha_actualizacion) VALUES (1,1,1,2,1,'RH','2020-09-12 00:00:00','2020-09-12 0
Falta inserción de Roles, rolesuser, SaldoAhorros, SaldoPrestamos y prestamos

2020-09-20 18:05 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/repositories/AtributoSolicitudRepository.java
> +public interface AtributoSolicitudRepository extends CrudRepository<AtributoSolicitud, Integer>{
cambiar   `CrudRepository` por `JpaRepository`

2020-09-20 18:06 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/repositories/CatalogoPropiedadRepository.java
> +public interface CatalogoPropiedadRepository extends CrudRepository<CatalogoPropiedad, Integer>{
cambiar   `CrudRepository` por `JpaRepository`

2020-09-20 18:06 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/repositories/SolicitudRepository.java
> +public interface SolicitudRepository extends CrudRepository<Solicitud, Integer>{
cambiar   `CrudRepository` por `JpaRepository`

2020-09-20 18:06 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/repositories/ValidacionRepository.java
> +public interface ValidacionRepository  extends CrudRepository<Validacion, Integer>{
cambiar   `CrudRepository` por `JpaRepository`

2020-09-20 18:09 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/services/CatalogoPropiedadService.java
> +			throw new ResponseStatusException(HttpStatus.NOT_FOUND, String.format("No hay CAT_PROPIEDADES con tipo %s", tipo));
bien, aunque creo que seria un mejor mensaje No hay catalogos  del  tipo {tipo}

2020-09-20 18:12 UTC, ralfdemoledor commented on src/main/java/com/business/cybord/services/RolService.java
> +		;
🤨 ;

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/ValidacionService.java
> +	ValidacionRepository repositoryValidacion;
Atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/ValidacionService.java
> +	SolicitudMapper mapper;
Atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	SolicitudService service;
Los atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	UsuariosService serviceUsuario;
Los atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	ValidacionService validacionService;
Los atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +	ValidacionService service;
Los atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +	UsuariosService serviceUsuario;
Los atributos de un bean son privados

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Rol.java
> +    @JoinColumn(name="id_usuario", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Solicitud.java
> +    @JoinColumn(name="id_usuario", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Validacion.java
> +    @JoinColumn(name="id_solicitud", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/DatosUsuario.java
> +    @JoinColumn(name="id_usuario", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/DatosUsuario.java
> +
borrar tantos enters

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Rol.java
> +    @JoinColumn(name="id_usuario", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Solicitud.java
> +    @JoinColumn(name="id_usuario", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/entities/Validacion.java
> +    @JoinColumn(name="id_solicitud", insertable=false, updatable=false)
identar

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/repositories/ValidacionRepository.java
> +public interface ValidacionRepository  extends CrudRepository<Validacion, Integer>{
Sobrescribrir el findAll() con  List<Validacion> findAll();

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +	///
borrar esto

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +	ValidacionService service;
hacerlo privado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +	UsuariosService serviceUsuario;
hacerlo privado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	SolicitudService service;
privado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	UsuariosService serviceUsuario;
privado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	ValidacionService validacionService;
privado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +	ValidacionService validacionService;
borrar si no se ocupa

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +		return new ResponseEntity<>(serviceUsuario.crearSolicitudUsuario(id_usuario, solicitudDto), HttpStatus.OK);
el servicio de estar en SolicitudService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +		return new ResponseEntity<>(serviceUsuario.actualizarSolicitudbyId(id_usuario, id_solicitud, solicitudDto), HttpStatus.OK);
el servicio de estar en SolicitudService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +		return new ResponseEntity<>(serviceUsuario.getSolicitudById(id_usuario,id_solicitud), HttpStatus.OK);
el servicio de estar en SolicitudService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/SolicitudContoller.java
> +		serviceUsuario.deleteSolicitudById(id_usuario, id_solicitud);
el servicio de estar en SolicitudService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/UsuariosController.java
> +import com.business.cybord.services.ValidacionService;
borrar import no usado

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +		return new ResponseEntity<>(serviceUsuario.crearValidacion(id_usuario,id_solicitud, validacionDto), HttpStatus.OK);
El metodo del servicio  ValidacionService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +		return new ResponseEntity<>(serviceUsuario.actualizarValidacionById(id_usuario, id_solicitud,id_validacion,validacionDto), HttpStatus.OK);
El método del servicio ValidacionService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +		return new ResponseEntity<>(serviceUsuario.getValidacionById(id_usuario, id_solicitud, id_validacion), HttpStatus.OK);
El método del servicio ValidacionService y no en usuario

2020-09-20 18:12 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/controllers/ValidacionController.java
> +		serviceUsuario.deleteValidacionById(id_usuario, id_solicitud, id_validacion);
El método del servicio ValidacionService y no en usuario

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +	public UsuariosDto insertarNuevoUsuario(UsuariosDto usuario) {
usar estandar o user  o usuario

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +		log.info("Buscando usuario con eee : {}", usuario.getEmail());
Que significa eee?

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +			Usuario datos = repository.save(mapper.getEntityFromUserDto(usuario));
cuidado con el nombrado  de variable

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +		entity.setDatosUsuario(usuario.getDatosUsuario());
no actualizar datos de usuario , tenemos un endpoint para eso

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +
quirar enters

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/UsuariosService.java
> +			throw new ResponseStatusException(HttpStatus.BAD_REQUEST,String.format("El dato %s no existe", datosUsuario.getTipoDato()));
poner llaves e identar

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/SolicitudService.java
> +	SolicitudRepository repositorySolicitud;
private

2020-09-20 18:24 UTC, eddypeacegamer commented on src/main/java/com/business/cybord/services/SolicitudService.java
> +	SolicitudMapper mapper;
private

2020-09-20 19:52 UTC, Eddd1e commented on src/main/java/com/business/cybord/services/ValidacionService.java
> +		repositoryValidacion.findAll().forEach(validaciones::add);
el jparepository si, pero el crudrepository no, igual ya lo cambie a jpa

2020-09-22 03:05 UTC, ralfdemoledor approved these changes

2020-09-23 00:56 UTC, merged